### PR TITLE
Install libarchive from Conda defaults channel.

### LINKED ISSUE #4: unpin libarchive
We require to monitor the stability of the `conda-forge` build of `libarchive` and unpin when safe to do so.

Reference: https://github.com/SciTools/workflows/pull/3

### PR DESCRIPTION
**Pull request by trexfeathers**
Closes #4 

I tested this a couple of months ago and the problem discussed in #3 does not occur if `libarchive` is installed from the default channel instead of conda-forge.

### CODE REVIEW

**Comment by trexfeathers** [comment]
Sorry I blanked out and didn't notice the original comment until I duplicated it 🙄

**Review by bjlittle — APPROVED** [review]

**Comment by bjlittle** [comment]
@trexfeathers Thanks, let's give it a whirl :+1:

**Comment by trexfeathers** [comment]
No luck!

https://github.com/SciTools/python-stratify/actions/runs/4510682971/jobs/7941924888#step:3:342

I'm also skeptical about using `conda install -y --no-update-deps -c conda-forge mamba conda-lock` as that might create problems for other packages that NEED to be changed.

**Comment by trexfeathers** [comment]
We could try: `conda install -y -c conda-forge -c defaults mamba conda-lock libarchive=3.6.2=b4bd9a0_1`

As I understand, this will make the install prefer `conda-forge`, unless it can't find it there in which case it will fall back on `defaults`.

I will test locally....

**Comment by trexfeathers** [comment]
> We could try: `conda install -y -c conda-forge -c defaults mamba conda-lock libarchive=3.6.2=hb4bd9a0_1`
> 
> As I understand, this will make the install prefer `conda-forge`, unless it can't find it there in which case it will fall back on `defaults`.
> 
> I will test locally....

This would work if we needed it.

**Pull request merged**
